version: '3.4'

services:
  pdv:
    image: ${DOCKER_REGISTRY}pdv
    build:
      context: .
      dockerfile: src/pdv/Dockerfile
    environment:
      mongo:database: pdv
      mongo:host: mongo
      mongo:port: 27017
    secrets:
      - source: mongo_user
        target: mongo:user
      - source: mongo_password
        target: mongo:password

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: pdv
      MONGO_INITDB_ROOT_PASSWORD: pdvpwd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: pdv
      ME_CONFIG_MONGODB_ADMINPASSWORD: pdvpwd

secrets:
  mongo_user:
    file: ./secrets/mongo_user.txt
  mongo_password:
    file: ./secrets/mongo_password.txt
